CREATE TABLE `Loai_Laptop` (
	`ID_Loai` VARCHAR(255) NOT NULL UNIQUE,
	`TenSP` VARCHAR(255),
	`GiaBan` BIGINT,
	`Hang` VARCHAR(255),
	`CPU` VARCHAR(255),
	`RAM` INTEGER,
	`GPU` VARCHAR(255),
	`HinhAnh` VARCHAR(255),
	`KichThuoc` VARCHAR(255),
	`KhuyenMai` VARCHAR(255),
	PRIMARY KEY(`ID_Loai`)
);


CREATE TABLE `ChiTietLaptop` (
	`MaSP` VARCHAR(255) NOT NULL UNIQUE,
	`GiaNhap` BIGINT,
	`NgayBan` DATETIME,
	`LoaiLaptop` VARCHAR(255),
	PRIMARY KEY(`MaSP`)
);


CREATE TABLE `Hang` (
	`ID_Hang` VARCHAR(255) NOT NULL UNIQUE,
	`TenHang` VARCHAR(255),
	`DiaChi` VARCHAR(255),
	`SDT` VARCHAR(255),
	PRIMARY KEY(`ID_Hang`)
);


CREATE TABLE `KhuyenMai` (
	`ID_KhuyenMai` VARCHAR(255) NOT NULL UNIQUE,
	`TenKhuyenMai` VARCHAR(255),
	`MucGiamGia` INTEGER,
	`MoTaKM` VARCHAR(255),
	`ThoiGianBatDau` DATETIME,
	`ThoiGianKetThuc` DATETIME,
	`ThoiGianTaoKM` DATETIME,
	PRIMARY KEY(`ID_KhuyenMai`)
);


CREATE TABLE `NhanVien` (
	`ID_NhanVien` VARCHAR(255) NOT NULL UNIQUE,
	`TenNV` VARCHAR(255),
	`NgaySinh` VARCHAR(255),
	`SDT` VARCHAR(255),
	`DiaChi` VARCHAR(255),
	`GioiTinh` BOOLEAN,
	`CCCD` VARCHAR(255),
	`Email` VARCHAR(255),
	PRIMARY KEY(`ID_NhanVien`)
);


CREATE TABLE `TaiKhoan` (
	`TenDN` VARCHAR(255) NOT NULL UNIQUE,
	`MatKhau` VARCHAR(255),
	`Quyen` VARCHAR(255),
	PRIMARY KEY(`TenDN`)
);


CREATE TABLE `Quyen` (
	`ID_Quyen` VARCHAR(255) NOT NULL UNIQUE,
	`ChiTietQuyen` VARCHAR(255),
	PRIMARY KEY(`ID_Quyen`)
);


CREATE TABLE `KhachHang` (
	`ID_KhachHang` VARCHAR(255) NOT NULL UNIQUE,
	`TenKH` VARCHAR(255),
	`DiaChiKH` VARCHAR(255),
	`SDT` VARCHAR(255),
	`TichDiem` INTEGER,
	PRIMARY KEY(`ID_KhachHang`)
);


CREATE TABLE `HoaDon` (
	`ID_HoaDon` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`MaNV` VARCHAR(255),
	`MaKH` VARCHAR(255),
	`NgayLap` DATETIME,
	`TongTien` BIGINT,
	`TienGiam` BIGINT,
	`TienNhan` BIGINT,
	`TienThoi` BIGINT,
	PRIMARY KEY(`ID_HoaDon`)
);


CREATE TABLE `ChiTietHoaDon` (
	`ID_SP` VARCHAR(255) NOT NULL,
	`ID_HoaDon` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY(`ID_SP`, `ID_HoaDon`)
);


CREATE TABLE `PhieuNhap` (
	`ID_PhieuNhap` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`ID_NhanVien` VARCHAR(255),
	`ID_NCC` VARCHAR(255),
	`NgayNhap` DATETIME,
	`TongTien` BIGINT,
	`TienTra` BIGINT,
	`TienThoi` BIGINT,
	PRIMARY KEY(`ID_PhieuNhap`)
);


CREATE TABLE `ChiTietPhieuNhap` (
	`ID_SP` VARCHAR(255) NOT NULL,
	`ID_PhieuNhap` BIGINT NOT NULL UNIQUE,
	PRIMARY KEY(`ID_SP`, `ID_PhieuNhap`)
);


ALTER TABLE `ChiTietLaptop`
ADD FOREIGN KEY(`LoaiLaptop`) REFERENCES `Loai_Laptop`(`ID_Loai`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Loai_Laptop`
ADD FOREIGN KEY(`Hang`) REFERENCES `Hang`(`ID_Hang`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Loai_Laptop`
ADD FOREIGN KEY(`KhuyenMai`) REFERENCES `KhuyenMai`(`ID_KhuyenMai`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `TaiKhoan`
ADD FOREIGN KEY(`TenDN`) REFERENCES `NhanVien`(`ID_NhanVien`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `TaiKhoan`
ADD FOREIGN KEY(`Quyen`) REFERENCES `Quyen`(`ID_Quyen`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `HoaDon`
ADD FOREIGN KEY(`MaNV`) REFERENCES `NhanVien`(`ID_NhanVien`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `HoaDon`
ADD FOREIGN KEY(`MaKH`) REFERENCES `KhachHang`(`ID_KhachHang`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ChiTietHoaDon`
ADD FOREIGN KEY(`ID_HoaDon`) REFERENCES `HoaDon`(`ID_HoaDon`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ChiTietHoaDon`
ADD FOREIGN KEY(`ID_SP`) REFERENCES `ChiTietLaptop`(`MaSP`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ChiTietPhieuNhap`
ADD FOREIGN KEY(`ID_SP`) REFERENCES `ChiTietLaptop`(`MaSP`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ChiTietPhieuNhap`
ADD FOREIGN KEY(`ID_PhieuNhap`) REFERENCES `PhieuNhap`(`ID_PhieuNhap`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PhieuNhap`
ADD FOREIGN KEY(`ID_NhanVien`) REFERENCES `NhanVien`(`ID_NhanVien`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PhieuNhap`
ADD FOREIGN KEY(`ID_NCC`) REFERENCES `Hang`(`ID_Hang`)
ON UPDATE NO ACTION ON DELETE NO ACTION;